hl.on("hyprland.start", function()
  hl.exec_cmd("sh -lc 'quickshell --path \"$HOME/.config/quickshell/shell.qml\"'")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
