require("monitors")
require("programs")
require("autostart")
require("environment")
require("permissions")
require("appearance")
require("layout")
require("windowrules")
require("input")
require("keybindings")

-- HyprMod managed settings. Keep this late so generated overrides still win.
require("hyprland-gui")

-- Wallpaper/theme colors generated by matugen. Keep after HyprMod so the active theme wins.
require("theme")
