# hyprlock configuration
general {
    no_fade_in = false
    lock_color = rgba(110, 148, 179, 100)
    lock_color_regex = \ppurge\s+\d+s
    fade_in = 2
    misc {
        unique = true
    }
}

background {
    monitor =
    path = screenshot
    color = rgba(255, 200, 0, 0.1)
    blur_passes = 2 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    valocity = 0.0
}

image {
    monitor =
    path = /home/thibaud/.config/hypr/profile.jpg
    size = 150
    rotate = 0
    reload_time = 0
    position = 0, 200
    color = rgba(200, 200, 200, 1.0)
    center = true
    border_size = 4
    border_color = rgba(106, 111, 125, 1.0)
    rotate = 0
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(150, 140, 240)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_out = 10
    outline_color = rgba(150, 140, 240, 0.5)
    text = <i>Password...</i>
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
}
