-- Generated by HyprMod.

hl.config({
  general = {
    col = {
      active_border = { colors = { "0xff77767b", "0xff3d3846" }, angle = 45 },
    },
    gaps_out = 10,
  },
  gestures = {
    workspace_swipe_invert = false,
  },
})
