# Window and workspace rules.

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    name = workspace-web-and-comms

    match:class = ^(firefox|zen|zen-browser|LibreWolf|librewolf|Brave-browser|brave-browser|google-chrome|chromium|discord|vesktop|WebCord|teams-for-linux|Microsoft Teams.*|microsoft teams.*)$

    workspace = 1
}

windowrule {
    name = workspace-games

    match:class = ^(steam|Steam|steam_app_[0-9]+|lutris|net\.lutris\.Lutris|heroic|Heroic|com\.heroicgameslauncher\.hgl|bottles|com\.usebottles\.bottles)$

    workspace = 2
}

windowrule {
    name = workspace-dev

    match:class = ^(Alacritty|kitty|foot|com\.mitchellh\.ghostty.*|code|Code|code-oss|Code - OSS|codium|VSCodium)$

    workspace = 3
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = terminal-opacity

    match:class = ^(Alacritty|kitty|foot|com\.mitchellh\.ghostty.*)$

    opacity = 0.97 0.9
}

windowrule {
    name = float-center-impala

    match:class = ^com\.mitchellh\.ghostty\.impala$

    float = yes
    center = yes
}

windowrule {
    name = float-center-wiremix

    match:class = ^com\.mitchellh\.ghostty\.wiremix$

    float = yes
    center = yes
}

windowrule {
    name = float-center-bluetui

    match:class = ^com\.mitchellh\.ghostty\.bluetui$

    float = yes
    center = yes
}

windowrule {
    name = float-center-editor

    match:class = ^com\.mitchellh\.ghostty\.editor$

    float = yes
    center = yes
}

windowrule {
    name = float-center-dns

    match:class = ^com\.mitchellh\.ghostty\.dns$

    float = yes
    center = yes
}

windowrule {
    name = float-center-ssh-usb

    match:class = ^com\.mitchellh\.ghostty\.ssh-usb$

    float = yes
    center = yes
}

windowrule {
    name = float-center-about

    match:class = ^com\.mitchellh\.ghostty\.about$

    float = yes
    center = yes
    size = 900 620
}
