background = #151218
foreground = #ffffff
selection-background = #e6d5ff
selection-foreground = #2d1a50
cursor-color = #e6d5ff

palette = 0=#151218
palette = 1=#ffd2cc
palette = 2=#e3d8f1
palette = 3=#ffd0db
palette = 4=#e6d5ff
palette = 5=#e6d5ff
palette = 6=#e3d8f1
palette = 7=#e7e0e8
palette = 8=#b6b0ba
palette = 9=#ffd2cc
palette = 10=#e3d8f1
palette = 11=#ffd0db
palette = 12=#e6d5ff
palette = 13=#e6d5ff
palette = 14=#e3d8f1
palette = 15=#ffffff
palette-generate = true
