-- Generated by theme-switch nord.

hl.config({
  general = {
    col = {
      active_border = { colors = { "rgba(81a1c1ee)", "rgba(88c0d0ee)" }, angle = 45 },
      inactive_border = "rgba(4c566aaa)",
    },
  },
  decoration = {
    shadow = {
      color = "rgba(000000ee)",
    },
  },
})
