-- Generated by matugen. Do not edit in ~/.config/hypr; edit dotfiles/matugen/templates instead.

hl.config({
  general = {
    col = {
      active_border = { colors = { "rgba({{ colors.primary.dark.hex_stripped }}ee)", "rgba({{ colors.secondary.dark.hex_stripped }}ee)" }, angle = 45 },
      inactive_border = "rgba({{ colors.outline.dark.hex_stripped }}aa)",
    },
  },
  decoration = {
    shadow = {
      color = "rgba({{ colors.shadow.dark.hex_stripped }}ee)",
    },
  },
})
